apiVersion: v1
kind: Service
metadata:
  name: kong-dbless
spec:
  type: NodePort
  ports:
    - name: kong-proxy-http
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: kong-proxy-https
      port: 8443
      targetPort: 8443
      protocol: TCP
  selector:
    app: kong-dbless