_format_version: "1.1"

services:
  - name: my-service
    url: https://sbx09-api.fftech.info/v1/
    plugins:
      - name: r8limiter
        config:
          server:
            host: localhost
            port: 8082
            timeout: 500
          domain: kong
          descriptors:
            - jwt_claims:
              - claim: client_tenantId
                key: tenant_id
            - ip_address: true
    routes:
      - name: any-route
        paths:
          - /
