apiVersion: v1
kind: Service
metadata:
  name: service-r8limiter
spec:
  selector:
    app: r8limiter
  type: NodePort
  ports:
    - name: grpc
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
